name: Push main build

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      REPOSITORY: ${{ secrets.ACR_NAME }}.azurecr.io
      IMAGE: graphql-server
    steps:
      - uses: actions/checkout@v2
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to Azure Container Registry
        env:
          ACR_NAME: ${{ secrets.ACR_NAME }}
        run: az acr login --name $ACR_NAME
      - name: Run Docker build
        run: docker build -t $REPOSITORY/$IMAGE:main .
      - name: Push image to repository
        run: docker push $REPOSITORY/$IMAGE:main
